# Generated by Django 5.0.3 on 2024-05-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("sub_title", models.CharField(max_length=150)),
                ("background_image", models.ImageField(upload_to="portfolio/")),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name="baner",
            name="background_image",
            field=models.ImageField(upload_to="baner/"),
        ),
    ]
