# Generated by Django 5.0.3 on 2024-05-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_portfolio_alter_baner_background_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_image", models.ImageField(upload_to="transformation/")),
                ("second_image", models.ImageField(upload_to="transformation/")),
            ],
        ),
    ]
