# Generated by Django 5.0.3 on 2024-05-06 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_transformation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transformation",
            old_name="first_image",
            new_name="after",
        ),
        migrations.RenameField(
            model_name="transformation",
            old_name="second_image",
            new_name="before",
        ),
    ]
